#+TITLE: Bus Charging Schedule Simulated Annealing with MILP Constraints
#+DATE: \today
#+EMAIL: A01704744@usu.edu

#+LATEX_CLASS: article

# Theorems/Lemmas/Definition headers
#+LATEX_HEADER: \newtheorem{definition}{Definition}[section]

* Preliminaries
** Mixed Integer Linear Program
A mixed integer linear programming (MILP) problem is a class of constrained optimization in which one seeks to find a
set of continuous or integer values that maximizes or minimizes an objective function while satisfying a set of
constraints [[cite:&chen-2010-applied]]. Given an objective function $J$, decision variables (i.e. variables of
optimization) $x_j \in \mathbb{R}$ and $y_k \in \mathbb{Z}^+$, and input parameters $c_j, d_k, a_{ij}, g_{ik}, b_i \in \mathbb{R}$, a MILP has the
mathematical structure represented in autoref:eq:milp-structure [[cite:&chen-2010-applied]].

#+name: eq:milp-structure
\begin{equation}
\begin{array}{lll}
\text{Maximize}   & J = \sum_j c_j x_j + \sum_k d_k y_k            &                 \\
\text{subject to} & \sum_j a_{ij} x_j + \sum_k g_{ik} y_k  \le b_i & (i = 1,2,...,m) \\
                  & x_j \ge 0                                      & (j = 1,2,...,n) \\
                  & y_k \in \mathbb{Z^+}0                          & (k = 1,2,...,n) \\
\end{array}
\end{equation}

This formulation of the MILP is also referred to as "crisp". By this it is meant that each variable in the formulation
acts as an injective mapping to its number representation. In other words, no values on the formulation are fuzzy
[[cite:&kaur-2016-introd-fuzzy]].

** Fuzzy Sets Theory
This section introduces the notion of fuzzy numbers and some basic definitions. Concepts from this section are pulled
from [[cite:&zimmermann-2001-fuzzy-set;&das-2016-mathem-model;&yaghobi-2014-compar-fuzzy;&bello-2019-fuzzy-activ]].

*** Fuzzy Sets
Let's begin with what a fuzzy number is
not. A classical (crisp) set is defined as a collection of elements $x \in X$. Crisp sets are binary, either an element
either belongs in the set, or it does not [[cite:&zimmermann-2001-fuzzy-set]]. For a fuzzy set, what is known as the
characteristic functions applies various degrees of membership for elements of a given set.

[[cite:&zimmermann-2001-fuzzy-set]].
#+begin_definition
Let $X$ be a collection of objects (often called the universe of discourse [[cite:&bello-2019-fuzzy-activ]]). If $X$ is denoted
generically by $x$, then a fuzzy set $\tilde{A}$ in $X$ is a set of ordered pairs as shown in  autoref:eq:membership-function.

#+name: eq:membership-function
\begin{equation}
\tilde{A} = \{(x, \mu_{\tilde{A}}(x))| x\in X\}
\end{equation}

\noindent
$\mu_{\tilde{A}}$ is called the membership function where $\mu_{\tilde{A}}$ is the mapping $\mu_{\tilde{A}} : X \rightarrow
[0,1]$; which assigns a real number to the interval $[0,1]$. The value of $\mu_{\tilde{A}}$ represents the degree of
membership of $x$ in $\tilde{A}$.
#+end_definition

This paper will use fuzzy sets defined on the real numbers $\mathbb{R}$. The membership function describes the shape of
the fuzzy number. As an example, consider the following definition.

#+begin_definition
A fuzzy number that is represented by $\tilde{A} = (a,b,c)$ is said to be triangular if its membership function is
defined as autoref:eq:triangular-fuzzy-number.

#+name: eq:triangular-fuzzy-number
\begin{equation}
  \mu_{\tilde{A}}(x) =
  \begin{cases}
    \frac{(x-a)}{(b-a)} & a \le x \le b \\
    \frac{(d-x)}{(d-b)} & c \le x \le d \\
    0                   & \text{else}
  \end{cases}
\end{equation}
#+end_definition

#+begin_definition
The fuzzy set $tilte{A}$ in $\mathbb{R}$ is normal if $\text{max}_x \mu_{\tilde{A}}(x) = 1$.
#+end_definition

#+begin_definition
A fuzzy set $\tilde{A}$ in $\mathbb{R}$ is convex if and only if the membership function of $\tilde{A}$ satisfies the inequality

\begin{equation*}
\mu_{\tilde{A}}[\beta x_1 + (1-\beta)x_2] \ge \text{min}[\mu_{\tilde{A}}(x_1), \mu_{\tilde{A}}(x_2)]\; \forall x_1, x_2 \in \mathbb{R}\; \beta \in [0,1]
\end{equation*}
#+end_definition

#+begin_definition
A fuzzy number is a normal convex fuzzy set in $\mathbb{R}$.
#+end_definition

#+begin_definition
The triangular fuzzy number $\tilde{A}$ is nonnegative $\iff\; a \ge 0$.
#+end_definition

*** Fuzzy Arithmetic
If two triangular fuzzy numbers $\tilde{a}_1 = \{a_1, a_2, a_3\}$ and $\tilde{b}_1 = \{b_1, b_2, b_3\}$ are nonnegative
then the following operations are defined in autoref:eq:fuzzy-arithmetic.

#+name: eq:fuzzy-arithmetic
\begin{equation}
\begin{array}{lcl}
\tilde{a} \oplus \tilde{b} & = & (a_1 + b_1, a_2 + b_2, a_3 + b_3) \\
\tilde{a} \ominus \tilde{b} & = & (a_1 + b_3, a_2 + b_2, a_3 + b_1) \\
\tilde{a} \otimes \tilde{b} & = & (a_1 b_1, a_2 b_2, a_3 b_3) \\
\end{array}
\end{equation}

*** Comparing Fuzzy Numbers
Fuzzy numbers do not directly provide a method of ordering nor do they always provide an ordered set like real numbers
[[cite:&bello-2019-fuzzy-activ]]. There are multiple methods for ordering fuzzy numbers, each coming with advantages and
disadvantages. Different properties have been applied to justify comparison of fuzzy numbers, such as: preference,
rationality, and robustness [[cite:&jimenez-2007-linear-progr;&bello-2019-fuzzy-activ;&kaur-2016-introd-fuzzy]]. These
methods are commonly known as ranking functions or ordering functions
[[cite:&bello-2019-fuzzy-activ;&das-2016-mathem-model;&kaur-2016-introd-fuzzy]]. Commonly, including in this work, the First
index of Yager [[cite:&yager-1981-proced-order]] is used (autoref:eq:first-index-yager).

#+name: eq:first-index-yager
\begin{equation}
\mathfrak{R}(\tilde{A}) = \frac{\sum_i a_i}{|\tilde{A}|}
\end{equation}

\noindent
where $|\cdot|$ represents the cardinality of the fuzzy number. In words, autoref:eq:first-index-yager is merely the average
of the values in the fuzzy number.

** Fully Fuzzy Linear Programming
Much like the MILP, fully fuzzy linear programs (FFLP) it is a class of constrained optimization in which one seeks to
find a set of continuous variables that either maximizes or minimizes an objective function, $J$, while satisfying a set
of constraints. The key difference in FFLP is that it is designed to accommodate imprecise information
[[cite:&bello-2019-fuzzy-activ;&kaur-2016-introd-fuzzy]]. In FFLP, the parameters and decision variables are fuzzy and
linear. A general FFLP is represented as shown in autoref:eq:general-fflp. The subscripts $\cdot_e$, $\cdot_l$, and $\cdot_g$
indicate to equality, less than, and greater than constraints, respectively.

#+name: eq:general-fflp
\begin{equation}
\begin{array}{lll}
\text{Maximize}   & J = \sum_j \tilde{C}_j\tilde{X}_j              &                 \\
\text{subject to} & \sum_j \tilde{a}_{ej} \otimes \tilde{x}_j = \tilde{b}_e &  \forall e = 1,2,3,... \\
                  & \sum_j \tilde{a}_{lj} \otimes \tilde{x}_j \le \tilde{b}_l &  \forall l = 1,2,3,... \\
                  & \sum_j \tilde{a}_{gj} \otimes \tilde{x}_j \ge \tilde{b}_l &  \forall g = 1,2,3,...
\end{array}
\end{equation}

There are many methods of solving FFLP
[[cite:&bello-2019-fuzzy-activ;&kaur-2016-introd-fuzzy;&ebrahimnejad-2016-new-method;&nasseri-2013-fully]]; however, most
solution methods convert the fuzzy model into a crisp model that can be solved using traditional methods
[[cite:&bello-2019-fuzzy-activ]]. In [[cite:&nasseri-2013-fully;&bello-2019-fuzzy-activ]], the method of converting the FFLP
into a crisp MILP is simply by applying the ranking function to the objective function and breaking the constraints down
into a set of crisp constraints as shown in autoref:eq:nasseri-solution. The constraints are separated according to the
definition of fuzzy set multiplication defined in autoref:eq:fuzzy-arithmetic. The fuzzy number index is represented is
the exponent rather than the subscript to clearly distinguish between the indexed value in the fuzzy number and the
constraint index (i.e. $\tilde{A} = (a^1,a^2,a^3)$).

#+name: eq:nasseri-solution
\begin{equation}
\begin{array}{lll}
\text{Maximize}   & J = \mathfrak{R}\Big(\sum_j (c_j^1,c_j^2,c_j^3)(x_j^1,x_j^2,x_j^3)\Big) &\\
\text{subject to} & \sum_j a_{ej}^1 x_j^1 = b_e^1 &  \forall e = 1,2,3,... \\
                  & \sum_j a_{lj}^1 x_j^1 \le b_l^1 &  \forall l = 1,2,3,... \\
                  & \sum_j a_{gj}^1 x_j^1 \ge b_l^1  &  \forall g = 1,2,3,... \\
                  & \sum_j a_{ej}^2 x_j^2 = b_e^2 &  \forall e = 1,2,3,... \\
                  & \sum_j a_{lj}^2 x_j^2 \le b_l^2 &  \forall l = 1,2,3,... \\
                  & \sum_j a_{gj}^2 x_j^2 \ge b_l^2  &  \forall g = 1,2,3,... \\
                  & \sum_j a_{ej}^3 x_j^3 = b_e^3 &  \forall e = 1,2,3,... \\
                  & \sum_j a_{lj}^3 x_j^3 \le b_l^3 &  \forall l = 1,2,3,... \\
                  & \sum_j a_{gj}^3 x_j^3 \ge b_l^3  &  \forall g = 1,2,3,... \\
                  & x_j^2 - x_j^1 \ge 0         & x_j^3 - x_j^2 \ge 0 \\
\end{array}
\end{equation}

\noindent
To be more succinct, the FFLP can also equivalently be written as autoref:eq:nasseri-solution-condensed.

#+name: eq:nasseri-solution-condensed
\begin{equation}
\begin{array}{lll}
\text{Maximize}   & J = \mathfrak{R}\Big(\sum_j (c_j^1,c_j^2,c_j^3)(x_j^1,x_j^2,x_j^3)\Big) &\\
\text{subject to} & \sum_j a_{ej}^k x_j^k = b_e^k &  \forall e = 1,2,3,... \\
                  & \sum_j a_{lj}^k x_j^k \le b_l^k &  \forall l = 1,2,3,... \\
                  & \sum_j a_{gj}^k x_j^k \ge b_l^k  &  \forall g = 1,2,3,... \\
                  & x_j^2 - x_j^1 \ge 0         & x_j^3 - x_j^2 \ge 0 \\
                  & \forall k \in \{1,2,...\}        &                  \\
\end{array}
\end{equation}

Where $k$ has a max value equal to the cardinality to the type of fuzzy number being utilized. This can be further be
elaborated on by rewriting the inequality constraints as equality constraints by introducing slack as equality
constraints by introducing slack as equality constraints by introducing slack variables. This is useful as it
represents the formulation in a standard form [[cite:&chen-2010-applied;&vanderbei-2020-linear-progr]]. It also has the
slightly less useful benefit of providing the solver a set of equations called a hyperplane [[cite:&chen-2010-applied]].

The given method is called the Kumar and Kaurs method. Generally speaking, it is designed to solve FFLP problems with
inequality constraints having LR flat fuzzy numbers.

# Bibliography
bibliographystyle:plain
bibliography:~/Documents/literature/ref.bib,~/Documents/library/ref.bib

#  LocalWords:  Yager MILP FFLP hyperplane
