################################################################################
# ENVIRONTMENT
################################################################################
version: '3'

env:
  TARGET : fuzzy-pap.pdf
  DOC    : fuzzy-pap

includes:
  mpap:
    taskfile: ./sup-doc/milp-pap-paper-frontiers/Taskfile.yml
    dir: ./sup-doc/milp-pap-paper-frontiers

################################################################################
# RECIPES
################################################################################

tasks:

##==============================================================================
#
  default:
    cmds:
      - task: precheck
      - task: mpap:images
      - task: pdf

##==============================================================================
#
  pipeline:
    cmds:
      - task: precheck
      - task: set-version
      - task: pdf

##==============================================================================
#
  precheck:
    desc: "Make sure that all the dependencies are installed."
    cmds:
      - |
        echo "Checking the programs required for the build are installed..."
        latexmk --version >/dev/null 2>&1 && (echo "latexmk installed!") || (echo "ERROR: latexmk is required."; exit 1)
        pdflatex --version >/dev/null 2>&1 && (echo "pdflatex installed!") || (echo "ERROR: pdflatex is required."; exit 1)
    silent: true

##==============================================================================
#
  set-version:
    desc: "Dynamically sets the version of the document."
    vars:
      MAIN: fuzzy-pap.tex
      VERSION:
        sh: git describe --tags
    cmds:
      - |
        sed -i 's/\\date{\\today/\\date{\\today:{{.VERSION}}/' {{.MAIN}}
    silent: true

##==============================================================================
#
  pdf:
    desc: "Output {{.TARGET}} PDF."
    vars:
      DOC_SRC: fuzzy-pap.tex
    sources:
      - ./*.tex
    generates:
      - ./fuzzy-pap.pdf
    cmds:
      - |
        latexmk -f -interaction=nonstopmode \
                   -pdf -pdflatex="pdflatex --shell-escape %O %S" \
                   -bibtex {{.DOC_SRC}}
    silent: false

##==============================================================================
#
  update-modules:
    desc: "Update all the submodules"
    vars:
      DATE:
        sh: date +%Y-%m-%d
    cmds:
      - |
        git submodule foreach git pull origin main
        git commit -am "Update modules: {{.DATE}}"
        git push

##==============================================================================
#
  clean:
    desc: "Clean up the project."
    vars:
      DOC_SRC: fuzzy-pap.tex
    cmds:
      - task: mpap:clean
      - |
        # Clean up the document files
        rm -f {{.TARGET}}
        latexmk -silent -C {{.DOC_SRC}}
    silent: true
