* Introduction
This document outlines a fuzzy model of the Position Allocation Problem (PAP). The model utilizes Mixed Integer Linear
Programming (MILP) constraints to determine feasible charging schedules. The problem involves generating an optimal
charging schedule for a fleet of Battery Electric Buses (BEBs) based on a set of routes and a mix of fast and slow
chargers. The objective is to reduce the number of total chargers and reduce the amount of time spent charging. The
samples utilized are a subset of the UTA bus routes from which the route times and time spent at the station are derived.
This paper assumes an average discharge over a period from which an estimated discharge is calculated for each route,
$\Delta_i$. Furthermore, linear battery dynamics are also assumed. Linear battery dynamics are a valid assumption when the
state-of-charge (SOC) is below 80% charge [cite:@liu-2020-batter-elect].

The Fuzzy PAP (FPAP) expands upon the MILP-PAP by adding a layer of robustness to the model's solutions
[cite:@bello-2019-fuzzy-activ; @kaur-2016-introd-fuzzy]. By introducing fuzziness to the model, that allows a sense of
uncertainty to some of the parameters. In a realistic scenario, multiple factors such as technical problems, weather
conditions, road detours, among others, buses may arrive earlier or later than anticipated to the station/depot. For
crisp models, there is no sense of lateness or earliness, thus the model's solutions lose validity at the moment that
any buses do not adhere to the route time perfectly. Fuzzifying the models in turn produces a fuzzy solution that
encodes ranges of times that buses may arrive while still remaining a valid solution.

The paper proceeds as follows. [[#sec:fuzzy-preliminaries]] introduces some of the basic concepts of Mixed Integer Linear
Programming (MILP), fuzzy set theory, and Fully Fuzzy Linear Programming (FFLP). [[#sec:the-crisp-bap-and-pap]] introduces
the Berth Allocation Problem (BAP) from which the PAP and MILP-PAP are derived from. The MILP-PAP is also derived in
full. [[#sec:the-fuzzy-bap]] introduces and derives a Fuzzy BAP (FBAP) model. [[#sec:the-fuzzy-pap]] then adapts the PAP into
the FPAP by utilizing the results from the previous sections.
